// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChargeCredits(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChargeCredits'](arg1, arg2, arg3);
}

export function CheckForUpdates(arg1, arg2) {
  return window['go']['main']['App']['CheckForUpdates'](arg1, arg2);
}

export function CheckLicenseOnServer(arg1) {
  return window['go']['main']['App']['CheckLicenseOnServer'](arg1);
}

export function ClearSavedSession() {
  return window['go']['main']['App']['ClearSavedSession']();
}

export function GetHWID() {
  return window['go']['main']['App']['GetHWID']();
}

export function GetSavedEmail() {
  return window['go']['main']['App']['GetSavedEmail']();
}

export function LoginOnServer(arg1, arg2) {
  return window['go']['main']['App']['LoginOnServer'](arg1, arg2);
}

export function PerformMockOperation(arg1, arg2, arg3) {
  return window['go']['main']['App']['PerformMockOperation'](arg1, arg2, arg3);
}

export function RegisterOnServer(arg1, arg2) {
  return window['go']['main']['App']['RegisterOnServer'](arg1, arg2);
}

export function SaveEmail(arg1) {
  return window['go']['main']['App']['SaveEmail'](arg1);
}
