// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChargeCredits(arg1:string,arg2:number,arg3:string):Promise<string>;

export function CheckForUpdates(arg1:boolean,arg2:number):Promise<string>;

export function CheckLicenseOnServer(arg1:string):Promise<string>;

export function ClearSavedSession():Promise<boolean>;

export function GetHWID():Promise<string>;

export function GetSavedEmail():Promise<string>;

export function LoginOnServer(arg1:string,arg2:string):Promise<string>;

export function PerformMockOperation(arg1:string,arg2:string,arg3:number):Promise<string>;

export function RegisterOnServer(arg1:string,arg2:string):Promise<string>;

export function SaveEmail(arg1:string):Promise<boolean>;
